default_install_hook_types:
   - pre-commit
   - post-commit
   - post-checkout
   - commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        types:
          - python
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        types:
          - python
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-ll"]
        files: .py$
  - repo: git@github.com:mailergroup/pre-commit-conventional-commits.git
    # renovate: datasource=github-releases depName=mailergroup/pre-commit-conventional-commits
    rev: v1.0.1
    hooks:
      - id: pre-commit-conventional-commits
        stages: [commit-msg]
  - repo: git@github.com:mailergroup/pre-commit-branch-name-validation.git
    # renovate: datasource=github-releases depName=mailergroup/pre-commit-branch-name-validation
    rev: v1.1.0
    hooks:
      - id: pre-commit-branch-validation
        stages: [post-commit, post-checkout]
